Design footer section
SD-0224/frontend-final-2 pull request #19
Opened 2024-04-13 16:45 UTC by HamadaMAssi

2024-04-13 18:24 UTC, MohamedAlQadeery requested changes
i think you need to rename dividerStack to DividerStack so it will match our naming convention

2024-04-13 19:59 UTC, HamadaMAssi commented
Do you mean the file name or the component name?

2024-04-14 03:22 UTC, MohamedAlQadeery commented
the file name

2024-04-14 08:23 UTC, hebaali9 approved these changes

2024-04-14 09:06 UTC, hebaali9 approved these changes

2024-04-14 09:07 UTC, MohamedAlQadeery approved these changes

2024-04-14 09:09 UTC, merged